confucius_quotes = [
	"Wheresoever you go, go with all your heart.",
	"Hold faithfulness and sincerity as first principles.",
	"Success depends upon previous preparation, and without such preparation, there is sure to be failure.",
	"If you make a mistake and do not correct it, this is called a mistake.",
	"Fine words and an insinuating appearance are seldom associated with true virtue.",
	"The superior man, when resting in safety, does not forget that danger may come. When in a state of security he does not forget the possibility of ruin. When all is orderly, he does not forget that disorder may come. Thus his person is not endangered, and his States and all their clans are preserved.",
	"Ignorance is the night of the mind, but a night without moon and star.",
	"He who will not economize will have to agonize.",
	"The nobler sort of man emphasizes the good qualities in others, and does not accentuate the bad. The inferior does.",
	"A superior man is modest in his speech but exceeds in his actions.",
	"Study the past if you would define the future.",
	"It does not matter how slowly you go so long as you do not stop.",
	"If I am walking with two other men, each of them will serve as my teacher. I will pick out the good points of the one and imitate them, and the bad points of the other and correct them in myself.",
	"Men's natures are alike, it is their habits that carry them far apart.",
	"Everything has beauty, but not everyone sees it.",
	"Education breeds confidence. Confidence breeds hope. Hope breeds peace.",
	"If you look into your own heart, and you find nothing wrong there, what is there to worry about? What is there to fear?",
	"The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.",
	"Do not do to others what you do not want done to yourself.",
	"In a country well-governed, poverty is something to be ashamed of. In a country badly governed, wealth is something to be ashamed of.",
	"It does not matter how slowly you go as long as you do not stop.",
	"Choose a job you love, and you will never have to work a day in your life.",
	"It is easy to hate and it is difficult to love. This is how the whole scheme of things works. All good things are difficult to achieve, and bad things are very easy to get.",
	"Forget injuries, never forget kindnesses.",
	"He who knows all the answers has not been asked all the questions.",
	"When it is obvious that the goals cannot be reached, don't adjust the goals; adjust the action steps.",
	"The more man meditates upon good thoughts, the better will be his world and the world at large.",
	"Before you embark on a journey of revenge, dig two graves.",
	"Silence is a true friend who never betrays.",
	"Do not impose on others what you yourself do not desire.",
	"Faced with what is right, to leave it undone shows a lack of courage.",
	"To be able under all circumstances to practice five things constitutes perfect virtue; these five things are gravity, generosity of soul, sincerity, earnestness, and kindness.",
	"Be not ashamed of mistakes and thus make them crimes.",
	"When it is obvious that the goals cannot be reached, don’t adjust the goals, adjust the action steps.",
	"The man who says he can, and the man who says he can’t are both correct.",
	"When anger rises, think of the consequences.",
	"Real knowledge is to know the extent of one's ignorance.",
	"Life is really simple, but we insist on making it complicated.",
	"When we see men of a contrary character, we should turn inwards and examine ourselves.",
	"By nature, men are nearly alike; by practice, they get to be wide apart.",
	"In a country well governed, poverty is something to be ashamed of. In a country badly governed, wealth is something to be ashamed of.",
	"Wisdom, compassion, and courage are the three universally recognized moral qualities of men.",
	"To see what is right, and not to do it, is want of courage or of principle.",
	"He with whom neither slander that gradually soaks into the mind, nor statements that startle like a wound in the flesh, are successful may be called intelligent indeed.",
	"Better a diamond with a flaw than a pebble without.",
	"Don’t complain about the snow on your neighbor’s roof when your own doorstep is unclean.",
	"Have no friends not equal to yourself.",
	"What the superior man seeks is in himself; what the small man seeks is in others.",
	"They must often change who would be constant in happiness or wisdom.",
	"He who exercises government by means of his virtue may be compared to the north polar star, which keeps its place and all the stars turn towards it.",
	"Respect yourself and others will respect you.",
	"He who learns but does not think is lost! He who thinks but does not learn is in great danger.",
	"He who speaks without modesty will find it difficult to make his words good.",
	"The superior man understands what is right; the inferior man understands what will sell.",
	"I hear and I forget. I see and I remember. I do and I understand.",
	"The man who moves a mountain begins by carrying away small stones.",
	"Never give a sword to a man who can't dance.",
	"The funniest people are the saddest ones.",
	"The superior man is modest in his speech, but exceeds in his actions.",
	"It is easy to hate and it is difficult to love. This is how the whole scheme of things works. All good things are difficult to achieve; and bad things are very easy to get.",
	"The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
	"Without feelings of respect, what is there to distinguish men from beasts?",
	"You cannot open a book without learning something.",
]